/*
 * -------------------------------------------------------------
 *  Generated by: SDK Generator
 *  Author      : projectilegravity & 48ix
 *  Timestamp   : 2026-02-22 11:36:47
 *  Game        : Fortnite
 *  Version     : ++Fortnite+Release-39.50-CL-51043566
 * -------------------------------------------------------------
 */

#pragma once
#include <cstdint>

namespace SDK
{

struct Actor
{
public:
	static const uint32_t RootComponent = 0x1b0; // (Size: 0x8, Property: ObjectProperty)
};

struct Character
{
public:
	static const uint32_t Mesh = 0x330; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t bIsCrouched = 0x440; // (Size: 0x1, Property: BoolProperty, Mask: 0x2, Bit: 1)
};

struct FortItemDefinition
{
public:
	static const uint32_t ItemType = 0xa8; // (Size: 0x1, Property: EnumProperty)
	static const uint32_t PrimaryAssetIdItemTypeOverride = 0xa9; // (Size: 0x1, Property: EnumProperty)
	static const uint32_t Rarity = 0xaa; // (Size: 0x1, Property: EnumProperty)
};

struct FortPawn
{
public:
	static const uint32_t bIsDying = 0x728; // (Size: 0x1, Property: BoolProperty, Mask: 0x20, Bit: 5)
	static const uint32_t bIsDBNO = 0x841; // (Size: 0x1, Property: BoolProperty, Mask: 0x80, Bit: 7)
	static const uint32_t CurrentWeapon = 0x990; // (Size: 0x8, Property: ObjectProperty)
};

struct FortPickup
{
public:
	static const uint32_t PrimaryPickupItemEntry = 0x3a8; // (Size: 0x158, Property: StructProperty)
};

struct FortPlayerController
{
public:
	static const uint32_t TargetedFortPawn = 0x1830; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t LocationUnderReticle = 0x2a30; // (Size: 0x18, Property: StructProperty)
};

struct FortPlayerPawnAthena
{
public:
	static const uint32_t bIsSliding = 0x72b; // (Size: 0x1, Property: BoolProperty, Mask: 0x10, Bit: 4)
	static const uint32_t bIsSkydiving = 0x22c7; // (Size: 0x1, Property: BoolProperty, Mask: 0x1, Bit: 0)
};

struct FortPlayerState
{
public:
	static const uint32_t Platform = 0x440; // (Size: 0x10, Property: StrProperty)
};

struct FortPlayerStateAthena
{
public:
	static const uint32_t TeamIndex = 0x11b1; // (Size: 0x1, Property: ByteProperty)
	static const uint32_t KillScore = 0x11c8; // (Size: 0x4, Property: IntProperty)
};

struct FortPlayerStateComponent_Habanero
{
public:
	static const uint32_t RankedProgress = 0xd8; // (Size: 0x18, Property: StructProperty)
};

struct FortWeapon
{
public:
	static const uint32_t bIsReloadingWeapon = 0x3b9; // (Size: 0x1, Property: BoolProperty, Mask: 0x1, Bit: 0)
	static const uint32_t WeaponData = 0x5b8; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t AmmoCount = 0x10a4; // (Size: 0x4, Property: IntProperty)
};

struct GameInstance
{
public:
	static const uint32_t LocalPlayers = 0x38; // (Size: 0x10, Property: ArrayProperty)
};

struct GameStateBase
{
public:
	static const uint32_t PlayerArray = 0x2c8; // (Size: 0x10, Property: ArrayProperty)
};

struct Pawn
{
public:
	static const uint32_t PlayerState = 0x2d0; // (Size: 0x8, Property: ObjectProperty)
};

struct PlayerController
{
public:
	static const uint32_t AcknowledgedPawn = 0x358; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t NetConnection = 0x528; // (Size: 0x8, Property: ObjectProperty)
};

struct PlayerState
{
public:
	static const uint32_t bIsABot = 0x2ba; // (Size: 0x1, Property: BoolProperty, Mask: 0x8, Bit: 3)
	static const uint32_t PawnPrivate = 0x328; // (Size: 0x8, Property: ObjectProperty)
};

struct SceneComponent
{
public:
	static const uint32_t RelativeLocation = 0x140; // (Size: 0x18, Property: StructProperty)
	static const uint32_t RelativeRotation = 0x158; // (Size: 0x18, Property: StructProperty)
	static const uint32_t ComponentVelocity = 0x188; // (Size: 0x18, Property: StructProperty)
	static const uint32_t bComponentToWorldUpdated = 0x1a0; // (Size: 0x1, Property: BoolProperty, Mask: 0x1, Bit: 0)
};

struct World
{
public:
	static const uint32_t PersistentLevel = 0x40; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t NetDriver = 0x48; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t GameState = 0x1d8; // (Size: 0x8, Property: ObjectProperty)
	static const uint32_t OwningGameInstance = 0x250; // (Size: 0x8, Property: ObjectProperty)
};

struct Player
{
public:
	static const uint32_t PlayerController = 0x30; // (Size: 0x8, Property: ObjectProperty)
};

}

